[package]
name = "nemotron-asr-sys"
version = "0.1.0"
edition = "2021"
description = "Low-level FFI bindings for nemotron-asr.cpp"
license = "MIT"
repository = "https://github.com/ervanalb/nemotron-asr-rs"
homepage = "https://github.com/ervanalb/nemotron-asr-rs"
documentation = "https://docs.rs/nemotron-asr-sys"
readme = "../README.md"
keywords = ["speech-recognition", "asr", "nemotron", "ggml", "ffi"]
categories = ["artificial-intelligence", "multimedia::audio", "external-ffi-bindings"]
links = "nemotron_asr_sys"

[features]
default = ["vendored"]
vendored = ["dep:num_cpus"]
bindgen = ["dep:bindgen"]
ggml_backend_dl = ["vendored"]

[dependencies]

[build-dependencies]
bindgen = { version = "0.70", optional = true }
num_cpus = { version = "1.16", optional = true }
