/* automatically generated by rust-bindgen 0.70.1 */

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nemo_latency_mode {
    NEMO_LATENCY_PURE_CAUSAL = 0,
    NEMO_LATENCY_ULTRA_LOW = 1,
    NEMO_LATENCY_LOW = 6,
    NEMO_LATENCY_DEFAULT = 13,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_cache_config {
    pub att_left_context: i32,
    pub att_right_context: i32,
    pub cache_drop_size: i32,
    pub conv_kernel_size: i32,
    pub conv_cache_size: i32,
    pub d_model: i32,
    pub n_layers: i32,
    pub n_heads: i32,
    pub d_head: i32,
    pub subsampling_factor: i32,
    pub n_mels: i32,
    pub sample_rate: i32,
    pub hop_length: i32,
    pub decoder_hidden: i32,
    pub decoder_layers: i32,
    pub vocab_size: i32,
    pub blank_token: i32,
    pub drop_extra_pre_encoded: i32,
    pub last_channel_cache_size: i32,
    pub pre_encode_cache_size: i32,
    pub shift_mel_frames: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nemo_cache_config"][::std::mem::size_of::<nemo_cache_config>() - 84usize];
    ["Alignment of nemo_cache_config"][::std::mem::align_of::<nemo_cache_config>() - 4usize];
    ["Offset of field: nemo_cache_config::att_left_context"]
        [::std::mem::offset_of!(nemo_cache_config, att_left_context) - 0usize];
    ["Offset of field: nemo_cache_config::att_right_context"]
        [::std::mem::offset_of!(nemo_cache_config, att_right_context) - 4usize];
    ["Offset of field: nemo_cache_config::cache_drop_size"]
        [::std::mem::offset_of!(nemo_cache_config, cache_drop_size) - 8usize];
    ["Offset of field: nemo_cache_config::conv_kernel_size"]
        [::std::mem::offset_of!(nemo_cache_config, conv_kernel_size) - 12usize];
    ["Offset of field: nemo_cache_config::conv_cache_size"]
        [::std::mem::offset_of!(nemo_cache_config, conv_cache_size) - 16usize];
    ["Offset of field: nemo_cache_config::d_model"]
        [::std::mem::offset_of!(nemo_cache_config, d_model) - 20usize];
    ["Offset of field: nemo_cache_config::n_layers"]
        [::std::mem::offset_of!(nemo_cache_config, n_layers) - 24usize];
    ["Offset of field: nemo_cache_config::n_heads"]
        [::std::mem::offset_of!(nemo_cache_config, n_heads) - 28usize];
    ["Offset of field: nemo_cache_config::d_head"]
        [::std::mem::offset_of!(nemo_cache_config, d_head) - 32usize];
    ["Offset of field: nemo_cache_config::subsampling_factor"]
        [::std::mem::offset_of!(nemo_cache_config, subsampling_factor) - 36usize];
    ["Offset of field: nemo_cache_config::n_mels"]
        [::std::mem::offset_of!(nemo_cache_config, n_mels) - 40usize];
    ["Offset of field: nemo_cache_config::sample_rate"]
        [::std::mem::offset_of!(nemo_cache_config, sample_rate) - 44usize];
    ["Offset of field: nemo_cache_config::hop_length"]
        [::std::mem::offset_of!(nemo_cache_config, hop_length) - 48usize];
    ["Offset of field: nemo_cache_config::decoder_hidden"]
        [::std::mem::offset_of!(nemo_cache_config, decoder_hidden) - 52usize];
    ["Offset of field: nemo_cache_config::decoder_layers"]
        [::std::mem::offset_of!(nemo_cache_config, decoder_layers) - 56usize];
    ["Offset of field: nemo_cache_config::vocab_size"]
        [::std::mem::offset_of!(nemo_cache_config, vocab_size) - 60usize];
    ["Offset of field: nemo_cache_config::blank_token"]
        [::std::mem::offset_of!(nemo_cache_config, blank_token) - 64usize];
    ["Offset of field: nemo_cache_config::drop_extra_pre_encoded"]
        [::std::mem::offset_of!(nemo_cache_config, drop_extra_pre_encoded) - 68usize];
    ["Offset of field: nemo_cache_config::last_channel_cache_size"]
        [::std::mem::offset_of!(nemo_cache_config, last_channel_cache_size) - 72usize];
    ["Offset of field: nemo_cache_config::pre_encode_cache_size"]
        [::std::mem::offset_of!(nemo_cache_config, pre_encode_cache_size) - 76usize];
    ["Offset of field: nemo_cache_config::shift_mel_frames"]
        [::std::mem::offset_of!(nemo_cache_config, shift_mel_frames) - 80usize];
};
extern "C" {
    pub fn nemo_cache_config_get_chunk_mel_frames(config: *const nemo_cache_config) -> usize;
}
extern "C" {
    pub fn nemo_cache_config_get_shift_mel_frames_val(config: *const nemo_cache_config) -> usize;
}
extern "C" {
    pub fn nemo_cache_config_get_chunk_samples(config: *const nemo_cache_config) -> i32;
}
extern "C" {
    pub fn nemo_cache_config_get_latency_ms(config: *const nemo_cache_config) -> i32;
}
extern "C" {
    pub fn nemo_cache_config_get_valid_out_len(config: *const nemo_cache_config) -> i32;
}
extern "C" {
    pub fn nemo_cache_config_default() -> nemo_cache_config;
}
extern "C" {
    pub fn nemo_cache_config_with_latency(mode: nemo_latency_mode) -> nemo_cache_config;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_context {
    _unused: [u8; 0],
}
pub type nemo_context_ffi = nemo_context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nemo_stream_context {
    _unused: [u8; 0],
}
pub type nemo_stream_context_ffi = nemo_stream_context;
extern "C" {
    pub fn c_nemo_init_with_backend(
        model_path: *const ::std::os::raw::c_char,
        backend_name: *const ::std::os::raw::c_char,
    ) -> *mut nemo_context_ffi;
}
extern "C" {
    pub fn c_nemo_free(ctx: *mut nemo_context_ffi);
}
extern "C" {
    pub fn c_nemo_get_backend_name(ctx: *mut nemo_context_ffi) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn c_nemo_stream_init(
        ctx: *mut nemo_context_ffi,
        config: *const nemo_cache_config,
    ) -> *mut nemo_stream_context_ffi;
}
extern "C" {
    pub fn c_nemo_stream_process_incremental(
        sctx: *mut nemo_stream_context_ffi,
        audio: *const i16,
        n_samples: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn c_nemo_stream_finalize(
        sctx: *mut nemo_stream_context_ffi,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn c_nemo_stream_get_transcript(
        sctx: *mut nemo_stream_context_ffi,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn c_nemo_stream_reset(sctx: *mut nemo_stream_context_ffi);
}
extern "C" {
    pub fn c_nemo_stream_free(sctx: *mut nemo_stream_context_ffi);
}
extern "C" {
    pub fn c_nemo_free_string(str_: *mut ::std::os::raw::c_char);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_backend_device {
    _unused: [u8; 0],
}
pub type ggml_backend_dev_t = *mut ggml_backend_device;
extern "C" {
    pub fn ggml_backend_dev_name(device: ggml_backend_dev_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn ggml_backend_dev_count() -> usize;
}
extern "C" {
    pub fn ggml_backend_dev_get(index: usize) -> ggml_backend_dev_t;
}
extern "C" {
    pub fn ggml_backend_load_all();
}
